# Generated by Django 5.1.5 on 2025-02-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CricketPlayer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=200)),
                ('image_path', models.URLField(max_length=300)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('batting_style', models.CharField(blank=True, max_length=100, null=True)),
                ('bowling_style', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField()),
                ('continent_id', models.IntegerField()),
                ('continent_name', models.CharField(max_length=100)),
                ('country_id', models.IntegerField()),
                ('country_name', models.CharField(max_length=100)),
                ('country_image_path', models.URLField(max_length=300)),
            ],
        ),
    ]
