# Generated by Django 5.1.5 on 2025-02-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('height_cm', models.FloatField()),
                ('weight_kgs', models.FloatField()),
                ('positions', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('overall_rating', models.IntegerField()),
                ('potential', models.IntegerField()),
                ('value_euro', models.BigIntegerField()),
                ('wage_euro', models.BigIntegerField()),
                ('preferred_foot', models.CharField(blank=True, max_length=10, null=True)),
                ('international_reputation', models.IntegerField(blank=True, null=True)),
                ('weak_foot', models.IntegerField()),
                ('skill_moves', models.IntegerField()),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
